nome=input("Digite o nome do aluno: ")
universidade=input('Digite a instituição: ')
semestre = int(input('Informe o semestre: '))
media_mensalidade = float(input('Digite a média da mensalidade : R$ '))
print(nome + ' estuda na universidade' + universidade)
print('Está no ', semestre, '° semestre ')
print('A média da mensalidade é de : R$' + str(media_mensalidade))
print('O tipo da variável [nome] é : ', type(nome))
print('O tipo da variável [universidade] é : ', type(universidade))
print('O tipo da variável [somestre] é : ', type(semestre))
print('O tipo da variável [media_mensalidade] é : ', type(media_mensalidade))